### ISSUE TITLE
Lightcurves are not displayed correctly using Safari browser

### ISSUE THREAD

**Issue by janvanroestel** [fritz-marshal/fritz#190] opened 2021-03-05 21:06 UTC
**Describe the bug**

**To Reproduce**
Open the fritz marshall using Safari
Go to the Candidates page and select a program to load targets. No lightcurves are displayed for any object.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10774087/110173422-67dbad00-7db3-11eb-8087-856925f99207.png)

**Platform information:**
 - Fritz version: (find this in the [About](https://fritz.science/about) page)
 - Interface
Paula Szkody is browsing  on a mac airbook with Safari as browser

Fritz version: v0.9.dev0+git20210304.6d0fd1c+fritz.36c5fc7

**Comment by stefanv** [comment] 2021-03-05 22:59
Can you please see if there are any errors in the developer console? You open the console with Shift + ⌘ + J

**Comment by stefanv** [comment] 2021-03-05 22:59
I have to be frank, though, we don't do any testing on Safari, so it is possible that these problems will slip in from time to time.  It's probably safest to install Firefox or Chrome.

**Comment by janvanroestel** [comment] 2021-03-06 02:05
This issue was brought to my attention by Paula Szkody, I'll let her know to use Firefox or Chrome

**Comment by dmitryduev** [comment] 2021-10-05 01:25
Can't reproduce - works fine in Safari as far as I can tell:
![image](https://user-images.githubusercontent.com/7557205/135945943-06b1f1f4-633b-458e-9ed2-9cb16991a896.png)

Closing.

**Closed by dmitryduev** 2021-10-05 01:25 UTC
Labels: bug
