### ISSUE TITLE
API - maxRedshift issue

### ISSUE THREAD

**Issue by deckersm** [fritz-marshal/fritz#309] opened 2021-07-02 12:14 UTC
**Describe the bug**
I am trying to extract all objects of a certain classification up to a specified redshift (z=0.3) using the API but it will only return objects with a redshift up to 0.1.

**To Reproduce**
    endpoint = f'https://fritz.science/api/sources?savedAfter={savedAfter}&classifications={classifications}&maxRedshift={maxRedshift}&minRedshift=0.1'
    headers = {'Authorization': f'token {token}'} 
    
    response = requests.request('GET', endpoint, json=data, headers=headers)
    
**Expected behavior**
A json file with all the objects satisfying the stated condition (SNe Ia with redshifts up to 0.3)

**Platform information:**
 - Interface
   - I am using the API

**Comment by acrellin** [comment] 2021-07-02 13:19
@deckersm Thanks for the detailed issue report. We'll investigate and get this resolved ASAP.

**Comment by acrellin** [comment] 2021-07-02 16:00
@deckersm Can you please print the values of the various parameters you're using in the URL? i.e. `classifications`, `maxRedshift`, `savedAfter`

**Comment by acrellin** [comment] 2021-07-02 16:10
@deckersm I am unable to reproduce. See the below request and response data:
``` python
r = requests.get("https://fritz.science/api/sources?maxRedshift=0.3&minRedshift=0.1&pageNumber=1&numPerPage=100", headers={"Authorization": f"token {token_id}"})
```
and then 
``` python 
In [15]: redshifts = [source['redshift'] for source in r.json()['data']['sources']]

In [16]: min(redshifts)   
Out[16]: 0.1

In [17]: max(redshifts)   
Out[17]: 0.277
```

**Comment by acrellin** [comment] 2021-07-02 16:11
Perhaps there are simply no sources with redshift greater than 0.1 that match the rest of your search criteria.

**Comment by guynir42** [comment] 2022-03-29 20:04
Closing for now. @deckersm if this issue continues to be a problem let us know!

**Closed by guynir42** 2022-03-29 20:04 UTC
Labels: bug
