### ISSUE TITLE
Interactive finder is down 

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#201] opened 2021-03-12 01:21 UTC
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
When one attempts to use the interactive finder chart on fritz.science, one gets the car driving off the cliff

**To Reproduce**
https://fritz.science/source/ZTF21aajtfas/finder

**Expected behavior**
Expected to see the interactive finder 

**Screenshots**
<img width="1292" alt="Screen Shot 2021-03-11 at 5 21 16 PM" src="https://user-images.githubusercontent.com/2769632/110877472-551f1780-828e-11eb-8190-9bd856bfd7ae.png">

**Platform information:**
 - Fritz version: (find this in the [About](https://fritz.science/about) page)
v0.9.dev0+git20210311.42b8342+fritz.d604d27.

 - Interface
   - [ ] I am using the API
   - [ x] I am browsing on a desktop
   - [ ] I am browsing on a phone
   - [ ] I am browsing on a tablet

**Additional context**
Chrome

**Comment by dmitryduev** [comment] 2021-03-15 20:52
Can't reproduce, works fine now:
![Uploading image.png…]()
All the servers were down or something? Anyways, closing for now.

**Closed by dmitryduev** 2021-03-15 20:52 UTC
Labels: bug
