### ISSUE TITLE
Crosshairs on ZTF cutout not on transient position

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#179] opened 2021-03-03 00:34 UTC
The crosshairs are sometimes not on the transient position when the ZTF cutouts are not square in their dimensions 

**To Reproduce**
1. Go to https://fritz.science/source/ZTF21aamqgid

**Comment by dmitryduev** [comment] 2021-03-03 02:05
Closing as duplicate of https://github.com/skyportal/skyportal/issues/1706.

**Closed by dmitryduev** 2021-03-03 02:05 UTC
Labels: bug
