### ISSUE TITLE
Favorites page

### ISSUE THREAD

**Issue by cfremling** [fritz-marshal/fritz#102] opened 2020-11-13 05:22 UTC
To keep track of which sources will need e.g. spectroscopic followup in the future, an essential functionality on the Growth marshal was the ability to add and remove sources to a private favorites page for the user. This was of great help when for example a scanner was not sure if a source is a CV or not. In this case one could add the source to favorites, then go back in a few days to check how the lightcurve evolves before triggering SEDM. If it was indeed a CV, with one click it could be removed from favorites.
 This page could have the same basic look as the group_sources page

**Comment by dannygoldstein** [comment] 2020-11-13 05:30
Duplicate of https://github.com/skyportal/skyportal/issues/1310

**Closed by dannygoldstein** 2020-11-13 05:30 UTC
