### ISSUE TITLE
Display cross-matched objects from other catalogs on the offset plot

### ISSUE THREAD

**Issue by dmitryduev** [fritz-marshal/fritz#59] opened 2020-10-02 19:54 UTC
Could either call `/api/alerts/ztf/<objectId>/aux` and grab `cross_matches` from there, or better query K for that specific data (/aux potentially returns a ton of data) on the backend.
Use different markers for different surveys.

**Comment by profjsb** [comment] 2020-10-02 19:59
Pushing this to SP during candidate save (even if the xmatch wasn't part of the filter), in the form of altdata, seems to make the most sense.

**Comment by dmitryduev** [comment] 2020-10-02 20:07
@profjsb right. But might need to keep stuff like TNS in sync then.

**Comment by dannygoldstein** [comment] 2020-11-05 20:32
Duplicate of https://github.com/skyportal/skyportal/issues/1011

**Closed by dannygoldstein** 2020-11-05 20:32 UTC
