### ISSUE TITLE
filter page: failed to fetch data from kowalski

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#26] opened 2020-09-02 03:12 UTC
When I navigate to the filter overview page on private.caltech.edu/filter/13, I see:

<img width="1461" alt="Screen Shot 2020-09-01 at 8 11 47 PM" src="https://user-images.githubusercontent.com/2769632/91927852-71168080-ec8f-11ea-962e-13d783ed4552.png">

**Comment by dmitryduev** [comment] 2020-09-16 09:35
It's a feature, not a bug :) Well, not really, but to handle this properly, SP should learn how to differentiate errors, which will eventually happen. Closing for now.

**Closed by dmitryduev** 2020-09-16 09:35 UTC
