### ISSUE TITLE
`make`-based build system?

### ISSUE THREAD

**Issue by dannygoldstein** [fritz-marshal/fritz#12] opened 2020-07-01 02:28 UTC
Wanted to start a discussion about transitioning from a docker-based build system to `make` as default, following SP. The current build system takes quite a while to start the repo from fresh (~20 mins) and I think it can be done in ~10x less time than that. @dmitryduev what are the blockers for this? 

cc @stefanv @profjsb @acrellin

**Comment by stefanv** [comment] 2020-07-01 07:44
The problem is that you then need to install all of Kowalski's dependencies: mongo, Traefik, Kafka.  I think the first two are fairly easy, but Kafka is quite painful.

That said, no reason why you cannot spin up Kowalski using the Docker mechanism and run SkyPortal locally for development work.

**Comment by dmitryduev** [comment] 2020-07-01 08:20
@dannygoldstein Just like @stefanv said -- it's mostly because it's painful to deal with jdk and kafka, especially for the testing purposes. A fresh start does indeed take quite a while, but once you have a lot of cached docker layers, a build takes the same 10x less time.
Also, dockerized K + local SP is exactly the way I use for F dev.

**Comment by dmitryduev** [comment] 2020-09-23 00:29
Doesn't look like were are going to do this, so closing for now.

**Closed by dmitryduev** 2020-09-23 00:29 UTC
