### ISSUE TITLE
Transient photometry only visible for "chosen" people

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz#125] opened 2020-12-04 12:43 UTC
Hi,

ZTF20acuzydz was shared with the infant SN filter. Jesper and I can see the photometry, but Mattia Bulla (same institute) Mickael Rigault and Kate Maguire do not see any photometry. This is a major issue. It would be terrific if you could fix this problem ASAP. :) Otherwise, this will impede us in catching the youngest SNe that are only 1-2 days old.

Screenshots are attached.

Cheers,

Steve

<img width="734" alt="Screenshot 2020-12-04 at 13 30 23" src="https://user-images.githubusercontent.com/11585543/101164968-244b9880-3636-11eb-82e2-27b98d683666.png">
![image_2](https://user-images.githubusercontent.com/11585543/101164976-26155c00-3636-11eb-884d-4f0033b953e3.jpg)

**Comment by steveschulze** [comment] 2020-12-04 12:46
there is a problem with the second image. you can find it at https://fritz-marshal.slack.com/archives/CTJCZ1PPS/p1607085941360300?thread_ts=1607085818.360100&cid=CTJCZ1PPS

**Comment by steveschulze** [comment] 2020-12-04 13:21
14:20 (Swedish time): We ingested the object to GM. Mattia can see the photometry on GM.

**Comment by acrellin** [comment] 2020-12-04 16:06
What groups do the people who cannot see the relevant data belong to?

**Comment by steveschulze** [comment] 2020-12-04 16:40
This is public MSIP data. Everybody should be able to see it. In fact, they can see them on the GROWTH Marshal.
________________________________

**Comment by acrellin** [comment] 2020-12-04 17:18
@steveschulze After looking into this a bit, it seems the issue is that you have not shared the photometry with the requisite groups for the other users to view it. In looking at a random photometry point associated with the source you cited, I see that it is shared with the following three groups:
```
Group name: Treasures Caltech -- Group nickname: au-caltech -- Group ID: 214
Group name: Treasures -- Group nickname: au -- Group ID: 215                
Group name: Treasures Public -- Group nickname: au-public -- Group ID: 223  
```
When I view the groups that Mattia, for example, belongs to, I see that they do not belong to any of the groups that the photometry are shared with. Mattia belongs to the following groups:
```
Group name: Sitewide Group -- Group nickname: None -- Group ID: 1                     
Group name: Redshift Completeness Factor -- Group nickname: rcf -- Group ID: 41       
Group name: Gamma Ray Bursts -- Group nickname: grb -- Group ID: 48                   
Group name: Infant Supernovae -- Group nickname: infant -- Group ID: 49               
Group name: Weizmann_Test -- Group nickname: WIS_Test -- Group ID: 65                 
Group name: Nuclear Transients -- Group nickname: None -- Group ID: 80                
Group name: Physics of Transients -- Group nickname: SWGSN -- Group ID: 88            
Group name: Goobar Research Group -- Group nickname: OKCAG -- Group ID: 116           
Group name: Type Ia Supernovae -- Group nickname: SNeIa -- Group ID: 177              
Group name: Weirdo thermonuclear SNe -- Group nickname: Weirdo Ia -- Group ID: 180    
Group name: SEDM Partnership-wide Group -- Group nickname: sedm2 -- Group ID: 209     
```
If you want the data to be shared publicly with all users, then you need to specify that it should be shared with the Sitewide Public Group (group ID = 1) when uploading photometry. The permissions checking is currently working as expected, closing this issue.

**Comment by dannygoldstein** [comment] 2020-12-04 18:38
@acrellin The problem here is that the photometry @steveschulze refers to is alert-stream photometry which should indeed be made visible to everyone on the site with the requisite stream access, regardless of their group, as soon as it is saved off the scanning page. Currently the scanning page saves the photometry to the group that the scanner saved the source to, so if another user who is not in that group tries to see the source, they cannot see any of the photometry, even if they have the proper stream access. This is indeed a bug on our side.

@steveschulze There is a fix in progress to address this issue, https://github.com/skyportal/skyportal/issues/1368, it is currently marked high priority and will be implemented soon. Thanks for bearing with us.

**Comment by steveschulze** [comment] 2020-12-04 19:00
@acrellin and @dannygoldstein thanks a lot for digging into this. This fix will be highly appreciated. :)

**Comment by acrellin** [comment] 2021-04-13 18:29
@dannygoldstein have you started development on this yet?

**Closed** 2021-04-28 20:37 UTC
